### ISSUE TITLE
Meaningful Readme

### ISSUE THREAD

**Issue by Xender** [Lightforger/danbooru-userscript#2]
It would be good to include summary from http://userscripts.org:8080/scripts/show/160537 or https://danbooru.donmai.us/forum_topics/9023 in the Readme (with link to the forum for cross-reference).

BBcode-to-Markdown converter may help with that (as D-text is fairly similar to BBcode).

**Comment by Lightforger** [comment]
Added link.
Since the script is meaningless without danbooru, should be enough.
