### ISSUE TITLE
userscripts.org:8080 history import.

### ISSUE THREAD

**Issue by Xender** [Lightforger/danbooru-userscript#3]
If you're interested into importing release history from http://userscripts.org:8080/scripts/versions/160537 into Git, then I can download and convert them into Git commits.

Next step would involve rebasing current Github history onto imported one - I can also help with/do that (I'd temporarily publish the repo to review as a fork alike Pull Requests are done).

The final step would be overwriting (git push --force) current master branch with the one rebased onto imported history.

It's the kind of operation which can complicate lives of people who forked or cloned the project repo, so if you're interested, it'd be good to perform it ASAP (and since this project is freshly moved into Github, and it has no forks (aside from mine temporary one), it's a good moment).

**Comment by Lightforger** [comment]
This all sounds very professional, but is it really worth it for such a small-scale script? (estimated number of users is 10-20, I'd be very surprised if anyone made a fork for anything besides a bugfix)
